server:
  port: 8090
  servlet:
    session:
      timeout: 604800s  # 设置sessoin过期时间 7天

spring:
  datasource:
    username: root
#    password: 123456
    password: MySQL8.0
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://liangtianyi.com:3306/networkrepair?serverTimezone=UTC&characterEncoding=UTF-8
    hikari:
      minimum-idle: 8
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 3000000
      connection-test-query: select 1
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true
#  redis:
#    host: 101.132.74.181 # Redis服务器地址
#    database: 0 # Redis数据库索引（默认为0）
#    port: 6379 # Redis服务器连接端口
#    password: Zk123456. # Redis服务器连接密码（默认为空）
#    jedis:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
#        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-idle: 8 # 连接池中的最大空闲连接
#        min-idle: 0 # 连接池中的最小空闲连接
#    timeout: 3000ms # 连接超时时间（毫秒）

mybatis:
  mapper-locations: classpath:mapper/*.xml

#配置日志
logging:
  #配置日志文件路径
  level:
    com.kkkoke.networkrepair.dao: debug #日志打印 sql 语句
    org.springfromework.web: debug
    org.hibernate: error
  file:
    path: /home/projects/baoxiu/log
    max-history: 90
#    path: /Users/kkkoke/IdeaProjects/network-repair/log